export const metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
}

export default function aboutPage() {
  //throw new Error('Deu ruim')
  return <div>aboutPage</div>
}
