import './globals.css'
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({
  weigth: ['420', '720'],
  subsets: ['latin'],
  variable: '--font-Open Sans',
})

export const metadata = {
  title: 'Mains Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} mx-24 bg-black text-slate-50 antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
